- name: Allow root to login MySQL from db2
  shell: |
    mysql --user root --password="{{ mysql_root_password }}" --execute="use mysql;UPDATE mysql.user SET host='%' WHERE user='root';"
  when: (ansible_hostname == "db2")

- name: Restart MySQl
  systemd:
    name: mysql
    state: restarted
  when: (ansible_hostname == "db2")

- name: Create user for wp database
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: 10.0.0.14
    name: wpuser
    password: wppassword
    priv: 'wp.*:ALL,GRANT'
    host: "{{ mysql_host_allowed }}"
    state: present
  when: (ansible_hostname == "db2")

- name: Flush privileges
  shell: mysql --user root --password={{ mysql_root_password }} --execute "FLUSH PRIVILEGES;"
  when: (ansible_hostname == "db2")